algorithm_config:
  name: fastspeech2
  type: fastspeech2
ckpt_dir: output/RAW_TEST_LibriTTS/ckpt
data_configs:
- data_dir: preprocessed_data/LibriTTS
  energy: &id001
    feature: phoneme_level
    normalization: true
  lang_id: en
  name: LibriTTS
  pitch: &id002
    feature: phoneme_level
    normalization: true
  subsets:
    test: data_config/LibriTTS/test.txt
    train: data_config/LibriTTS/train.txt
    val: data_config/LibriTTS/val.txt
  symbol_id: en
  text_cleaners:
  - english_cleaners
log_dir: output/RAW_TEST_LibriTTS/log
model_config:
  energy: *id001
  max_seq_len: 1000
  multi_speaker: false
  pitch: *id002
  transformer:
    conv_filter_size: 1024
    conv_kernel_size:
    - 9
    - 1
    decoder_dropout: 0.2
    decoder_head: 2
    decoder_hidden: 256
    decoder_layer: 6
    encoder_dropout: 0.2
    encoder_head: 2
    encoder_hidden: 256
    encoder_layer: 4
  variance_embedding:
    energy_quantization: linear
    n_bins: 256
    pitch_quantization: linear
  variance_predictor:
    dropout: 0.5
    filter_size: 256
    kernel_size: 3
  vocoder:
    model: HifiGAN
result_dir: output/RAW_TEST_LibriTTS/result
train_config:
  optimizer:
    batch_size: 16
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    grad_acc_step: 1
    grad_clip_thresh: 1.0
    lr: 0.001
    warm_up_step: 4000
    weight_decay: 0.0
  path:
    ckpt_path: output/RAW_TEST_LibriTTS/ckpt
    log_path: output/RAW_TEST_LibriTTS/log
    result_path: output/RAW_TEST_LibriTTS/result
  step:
    log_step: 100
    save_step: 10000
    synth_step: 1000
    total_step: 50000
    val_step: 2500
